name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: 'Build - Test - [Publish]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: cp README.md packages/vanilla-hcaptcha
      - name: 'Publish'
        if: contains('refs/heads/master', github.ref)
        run: lerna publish -y from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
